steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds','submit',
         '--tag','gcr.io/$PROJECT_ID/$_SERVICE']
  dir: 'org-level-recommendations-hub/ticketservice'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run','deploy','$_SERVICE',
         '--image','gcr.io/$PROJECT_ID/$_SERVICE',
         '--platform','managed',
         '--region','"us-central1"',
         '--allow-unauthenticated']
  dir: 'org-level-recommendations-hub/ticketservice'